---
language: python
services:
  - docker
python:
  - "3.7"
env:
  - UBUNTU_IMAGE_TAG: bionic
install:
  - pip install testinfra molecule docker
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
